import type { PlanningRuleSet, PlanningRule } from "../../types/rules.ts";

export const TEST_RULE_SET_ID = "OSC_SMARTCHECK_TEST_RULESET_V1";

export const TEST_RULES: PlanningRule[] = [
  // 1. RTD Zoning Rule
  {
    ruleId: "RULE-RTD-001",
    ruleSetId: TEST_RULE_SET_ID,
    code: "RTD-ZONING-01",
    name: "Pematuhan Zon Guna Tanah RTD Langkawi 2030",
    description: "Memastikan cadangan aktiviti pembangunan dibenarkan di bawah zon RTD semasa.",
    category: "RTD",
    developmentTypes: ["HOTEL", "COMMERCIAL", "MIXED_DEVELOPMENT"],
    applicability: { all: [] },
    ruleType: "SPATIAL_ZONE",
    inputKeys: ["rtd.primaryZone"],
    parameters: {
      allowedUses: ["HOTEL", "COMMERCIAL"],
      conditionalUses: ["MIXED_DEVELOPMENT"],
      prohibitedUses: ["HEAVY_INDUSTRIAL"],
    },
    severity: "CRITICAL",
    failureStatus: "NON_COMPLIANT",
    missingDataStatus: "INSUFFICIENT_DATA",
    sourceDocumentId: "DOC-RTD-LANGKAWI-2030",
    sourceDocumentVersion: "V2026.01",
    sourceClause: "Jadual Guna Tanah 3.1",
    sourcePage: 45,
    sourceTextExcerpt: "Aktiviti hotel dan perniagaan pelancongan adalah DIBENARKAN dalam Zon Perdagangan.",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    priority: 100,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 2. Hotel Car Parking Formula Rule
  {
    ruleId: "RULE-PARK-001",
    ruleSetId: TEST_RULE_SET_ID,
    code: "GPP-PARK-HOTEL-01",
    name: "Keperluan Tempat Letak Kereta Hotel",
    description: "Kiraan penyediaan tempat letak kereta hotel: 1 petak bagi setiap 4 bilik.",
    category: "PARKING",
    developmentTypes: ["HOTEL"],
    applicability: {
      all: [{ field: "developmentType", operator: "EQUALS", value: "HOTEL" }],
    },
    ruleType: "FORMULA",
    inputKeys: ["hotel.rooms", "parking.carProvided"],
    formula: {
      formulaType: "CEIL_DIVIDE_MULTIPLY",
      parameters: {
        roomsPerUnit: 4,
        parkingRequired: 1,
      },
    },
    parameters: {
      unit: "petak",
      roomsPerUnit: 4,
      parkingRequired: 1,
    },
    severity: "CRITICAL",
    failureStatus: "NON_COMPLIANT",
    missingDataStatus: "INSUFFICIENT_DATA",
    sourceDocumentId: "DOC-GPP-TLK-MPLBP",
    sourceDocumentVersion: "1.0",
    sourceClause: "4.2.1",
    sourcePage: 32,
    sourceTextExcerpt: "Hotel 4-bintang dan ke atas hendaklah menyediakan 1 petak kereta bagi setiap 4 bilik penginapan.",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    priority: 90,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 3. OKU Disabled Parking Minimum
  {
    ruleId: "RULE-PARK-002",
    ruleSetId: TEST_RULE_SET_ID,
    code: "GPP-PARK-OKU-01",
    name: "Penyediaan Minimum Petak OKU",
    description: "Penyediaan minimum 2 petak khas bagi Orang Kurang Upaya (OKU).",
    category: "PARKING",
    developmentTypes: ["HOTEL", "COMMERCIAL", "MIXED_DEVELOPMENT"],
    applicability: { all: [] },
    ruleType: "THRESHOLD_MIN",
    inputKeys: ["parking.disabledProvided"],
    parameters: {
      threshold: 2,
      unit: "petak",
    },
    severity: "MAJOR",
    failureStatus: "NON_COMPLIANT",
    missingDataStatus: "INSUFFICIENT_DATA",
    sourceDocumentId: "DOC-GPP-TLK-MPLBP",
    sourceDocumentVersion: "1.0",
    sourceClause: "4.5.1",
    sourcePage: 38,
    sourceTextExcerpt: "Minimum 2 petak OKU hendaklah disediakan berhampiran pintu masuk utama.",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    priority: 85,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 4. Motorcycle Parking Minimum
  {
    ruleId: "RULE-PARK-003",
    ruleSetId: TEST_RULE_SET_ID,
    code: "GPP-PARK-MOTO-01",
    name: "Penyediaan Minimum Petak Motosikal",
    description: "Penyediaan tempat letak motosikal sekurang-kurangnya 40 petak.",
    category: "PARKING",
    developmentTypes: ["HOTEL", "COMMERCIAL"],
    applicability: { all: [] },
    ruleType: "THRESHOLD_MIN",
    inputKeys: ["parking.motorcycleProvided"],
    parameters: {
      threshold: 40,
      unit: "petak",
    },
    severity: "MAJOR",
    failureStatus: "NON_COMPLIANT",
    missingDataStatus: "INSUFFICIENT_DATA",
    sourceDocumentId: "DOC-GPP-TLK-MPLBP",
    sourceDocumentVersion: "1.0",
    sourceClause: "4.6.1",
    sourcePage: 40,
    sourceTextExcerpt: "Penyediaan petak motosikal tidak kurang daripada 40 petak bagi cadangan hotel melebihi 100 bilik.",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    priority: 80,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 5. Open Space Percentage Minimum
  {
    ruleId: "RULE-OPEN-001",
    ruleSetId: TEST_RULE_SET_ID,
    code: "GPP-OPEN-SPACE-01",
    name: "Penyediaan Kawasan Lapang Minimum 10%",
    description: "Rizab kawasan lapang berfungsi sekurang-kurangnya 10% daripada keluasan keseluruhan tapak.",
    category: "OPEN_SPACE",
    developmentTypes: ["HOTEL", "HOUSING", "MIXED_DEVELOPMENT"],
    applicability: { all: [] },
    ruleType: "THRESHOLD_MIN",
    inputKeys: ["openSpace.percentage"],
    parameters: {
      threshold: 10.0,
      unit: "%",
    },
    severity: "CRITICAL",
    failureStatus: "NON_COMPLIANT",
    missingDataStatus: "INSUFFICIENT_DATA",
    sourceDocumentId: "DOC-GPP-KAWASAN-LAPANG",
    sourceDocumentVersion: "2.0",
    sourceClause: "2.1",
    sourcePage: 14,
    sourceTextExcerpt: "Keluasan kawasan lapang berfungsi sekurang-kurangnya 10% daripada jumlah keluasan skim pemajuan.",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    priority: 85,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },

  // 6. Plot Ratio Limit
  {
    ruleId: "RULE-RATIO-001",
    ruleSetId: TEST_RULE_SET_ID,
    code: "GPP-INTENSITY-PR-01",
    name: "Had Maksimum Nisbah Plot Komersial",
    description: "Nisbah plot pembangunan hotel / komersial tidak boleh melebihi 1:2.5.",
    category: "PLOT_RATIO",
    developmentTypes: ["HOTEL", "COMMERCIAL"],
    applicability: { all: [] },
    ruleType: "RATIO",
    inputKeys: ["intensity.plotRatio"],
    parameters: {
      maxRatio: 2.5,
    },
    severity: "CRITICAL",
    failureStatus: "NON_COMPLIANT",
    missingDataStatus: "INSUFFICIENT_DATA",
    sourceDocumentId: "DOC-RTD-LANGKAWI-2030",
    sourceDocumentVersion: "V2026.01",
    sourceClause: "Kawalan Intensiti 4.1",
    sourcePage: 58,
    sourceTextExcerpt: "Nisbah plot maksimum bagi Pusat Bandar Kuah adalah 1:2.5.",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    priority: 95,
    enabled: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
  },
];

export const TEST_RULE_SETS: Array<PlanningRuleSet & { rules: PlanningRule[] }> = [
  {
    ruleSetId: TEST_RULE_SET_ID,
    code: "GPP_MPLBP_SUITE_2026",
    name: "Set Peraturan Standard Perancangan MPLBP 2026 (Ujian)",
    description: "Kompilasi piawaian tempat letak kereta, kawasan lapang, nisbah plot dan RTD Langkawi.",
    category: "PARKING",
    jurisdiction: "MPLBP",
    authority: "Majlis Perbandaran Langkawi",
    version: "1.0.0",
    status: "ACTIVE",
    effectiveFrom: "2024-01-01",
    effectiveTo: null,
    sourceDocumentIds: ["DOC-GPP-TLK-MPLBP", "DOC-RTD-LANGKAWI-2030", "DOC-GPP-KAWASAN-LAPANG"],
    approvedBy: "SUPER_ADMIN",
    approvedAt: "2026-01-01T00:00:00.000Z",
    createdBy: "SYSTEM",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    checksum: "test-checksum-suite-2026",
    isTestOnly: true,
    rules: TEST_RULES,
  },
];
