/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Firestore } from "firebase-admin/firestore";
import { getAdminDb } from "../firebase/admin.ts";
import { DEMO_10_APPLICATIONS, DemoApplicationSeed } from "./demoData.ts";
export { DEMO_10_APPLICATIONS, type DemoApplicationSeed, getDemoApplication, getDemoSmartCheckForApp } from "./demoData.ts";

/**
 * Seeds or resets the 10 diverse demo applications in Firestore
 */
export async function seedDemoApplications(
  customDb?: Firestore
): Promise<{ seededCount: number; applications: DemoApplicationSeed[] }> {
  const db = customDb || getAdminDb();

  for (const app of DEMO_10_APPLICATIONS) {
    const appRef = db.collection("applications").doc(app.id);

    await appRef.set(
      {
        id: app.id,
        applicationNo: app.applicationNo,
        title: app.title,
        developmentType: app.developmentType,
        developmentCategory: app.developmentCategory,
        mukim: app.mukim,
        district: "Langkawi",
        state: "Kedah",
        status: app.status,
        currentVersion: app.currentVersion,
        applicantUid: app.applicantUid,
        applicantName: app.applicantName,
        consultantName: app.consultantName,
        estimatedCost: app.estimatedCost,
        remarks: app.remarks,
        createdAt: app.createdAt,
        updatedAt: app.updatedAt,
        landDetails: {
          lotNo: app.lotNo,
          mukim: app.mukim,
          district: "Langkawi",
          state: "Kedah",
          siteAreaSqm: app.siteAreaSqm,
        },
        location: {
          latitude: app.latitude,
          longitude: app.longitude,
        },
        project: {
          projectName: app.title,
          developmentType: app.developmentType,
          developmentCategory: app.developmentCategory,
          proposedUse: app.title,
          estimatedProjectValue: app.estimatedCost,
        },
        applicant: {
          applicantName: app.applicantName,
          applicantType: "COMPANY",
          companyName: app.applicantName,
          email: "pemohon@perunding.com",
          phone: "+604-9661234",
          address: "Pekan Kuah, 07000 Langkawi, Kedah",
        },
        consultant: {
          principalSubmittingPerson: app.consultantName,
          consultantCompany: app.applicantName,
          professionalRegistrationNo: "LAM/BEM/2026",
          email: "perunding@arkitek.com",
          phone: "+604-9665678",
        },
      },
      { merge: true }
    );
  }

  return {
    seededCount: DEMO_10_APPLICATIONS.length,
    applications: DEMO_10_APPLICATIONS,
  };
}

export function getDemoDocumentsForApp(id: string) {
  const app = getDemoApplication(id);
  return [
    {
      id: `doc-${app.id}-lcp`,
      documentId: `doc-${app.id}-lcp`,
      applicationId: app.id,
      documentType: "LCP" as const,
      fileName: `LCP_Pelan_Susunatur_${app.lotNo.replace(/\s+/g, "_")}_v${app.currentVersion}.0.pdf`,
      originalFileName: `LCP_Pelan_Susunatur_${app.lotNo.replace(/\s+/g, "_")}_v${app.currentVersion}.0.pdf`,
      storagePath: `applications/${app.id}/documents/LCP_v${app.currentVersion}.pdf`,
      version: app.currentVersion,
      isCurrent: true,
      fileSize: 14850200,
      mimeType: "application/pdf",
      checksum: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      status: "ACTIVE" as const,
      processingStatus: "COMPLETED" as const,
      supersedesDocumentId: null,
      uploadedBy: app.applicantUid,
      uploadedAt: app.createdAt,
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `doc-${app.id}-grant`,
      documentId: `doc-${app.id}-grant`,
      applicationId: app.id,
      documentType: "SITE_PLAN" as const,
      fileName: `Pelan_Tapak_${app.lotNo.replace(/\s+/g, "_")}_Mukim_${app.mukim}.pdf`,
      originalFileName: `Pelan_Tapak_${app.lotNo.replace(/\s+/g, "_")}_Mukim_${app.mukim}.pdf`,
      storagePath: `applications/${app.id}/documents/Pelan_Tapak.pdf`,
      version: 1,
      isCurrent: true,
      fileSize: 4250100,
      mimeType: "application/pdf",
      checksum: "8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
      status: "ACTIVE" as const,
      processingStatus: "COMPLETED" as const,
      supersedesDocumentId: null,
      uploadedBy: app.applicantUid,
      uploadedAt: app.createdAt,
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
  ];
}

export function getDemoFactsForApp(id: string) {
  const app = getDemoApplication(id);
  const isApp2 = app.id === "app-demo-002";
  const isApp3 = app.id === "app-demo-003";

  return [
    // 1. PROJECT
    {
      id: `fact-${app.id}-proj-1`,
      factId: `fact-${app.id}-proj-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "projectName",
      label: "Nama Projek Pemajuan",
      category: "PROJECT" as const,
      value: app.title,
      unit: null,
      normalizedValue: app.title,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.99,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.title,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 1,
          quotedText: `Tajuk Cadangan: ${app.title}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-proj-2`,
      factId: `fact-${app.id}-proj-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "applicantName",
      label: "Pemohon / Pemaju",
      category: "PROJECT" as const,
      value: app.applicantName,
      unit: null,
      normalizedValue: app.applicantName,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.applicantName,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 1,
          quotedText: `Pemaju: ${app.applicantName}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-proj-3`,
      factId: `fact-${app.id}-proj-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "consultantName",
      label: "Jururancang Bandar / Arkitek",
      category: "PROJECT" as const,
      value: app.consultantName,
      unit: null,
      normalizedValue: app.consultantName,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.consultantName,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 2,
          quotedText: `Disediakan oleh: ${app.consultantName}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-proj-4`,
      factId: `fact-${app.id}-proj-4`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "estimatedCost",
      label: "Anggaran Kos Pemajuan (RM)",
      category: "PROJECT" as const,
      value: app.estimatedCost,
      unit: "MYR",
      normalizedValue: app.estimatedCost,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.estimatedCost,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 3,
          quotedText: `Anggaran nilai keseluruhan projek adalah RM ${app.estimatedCost.toLocaleString()}.`,
          tableReference: "Jadual 1.2: Anggaran Kos",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 2. SITE
    {
      id: `fact-${app.id}-site-1`,
      factId: `fact-${app.id}-site-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "lotNo",
      label: "Nombor Lot Hakmilik",
      category: "SITE" as const,
      value: app.lotNo,
      unit: null,
      normalizedValue: app.lotNo,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.99,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.lotNo,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 3,
          quotedText: `Tapak cadangan terletak di ${app.lotNo}, Mukim ${app.mukim}, Langkawi.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-site-2`,
      factId: `fact-${app.id}-site-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "siteAreaSqm",
      label: "Keluasan Tapak (m²)",
      category: "SITE" as const,
      value: app.siteAreaSqm,
      unit: "SQM",
      normalizedValue: app.siteAreaSqm,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.99,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.siteAreaSqm,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 3,
          quotedText: `Jumlah keluasan tapak pemajuan adalah seluas ${app.siteAreaSqm.toLocaleString()} m².`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-site-3`,
      factId: `fact-${app.id}-site-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "landStatus",
      label: "Status Hakmilik & Pegangan",
      category: "SITE" as const,
      value: "Pajakan 99 Tahun (Leasehold)",
      unit: null,
      normalizedValue: "Pajakan 99 Tahun",
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "Pajakan 99 Tahun (Leasehold)",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 4,
          quotedText: `Status pegangan tanah adalah Pajakan 99 Tahun yang berakhir pada tahun 2115.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 3. LAND_USE
    {
      id: `fact-${app.id}-land-1`,
      factId: `fact-${app.id}-land-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "proposedLandUse",
      label: "Cadangan Guna Tanah Utama",
      category: "LAND_USE" as const,
      value: app.developmentType,
      unit: null,
      normalizedValue: app.developmentType,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.developmentType,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 5,
          quotedText: `Cadangan guna tanah yang dikemukakan adalah bagi tujuan ${app.developmentType}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-land-2`,
      factId: `fact-${app.id}-land-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "rtdZoning",
      label: "Pengezonan RTD Langkawi 2030",
      category: "LAND_USE" as const,
      value: `Zon Pembangunan ${app.developmentType} (Blok Perancangan BP 2)`,
      unit: null,
      normalizedValue: app.developmentType,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: `Zon Pembangunan ${app.developmentType} (Blok Perancangan BP 2)`,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 6,
          quotedText: `Menurut Rancangan Tempatan Daerah Langkawi 2030, tapak berada dalam zon pemajuan yang dibenarkan.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 4. INTENSITY
    {
      id: `fact-${app.id}-int-1`,
      factId: `fact-${app.id}-int-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "plotRatio",
      label: "Nisbah Plot (Plot Ratio)",
      category: "INTENSITY" as const,
      value: "1 : 2.5",
      unit: "RATIO",
      normalizedValue: 2.5,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "1 : 2.5",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 8,
          quotedText: `Nisbah plot yang dicadangkan ialah 1:2.5 selaras dengan piawaian kelas guna tanah.`,
          tableReference: "Jadual Intensiti Pembangunan",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-int-2`,
      factId: `fact-${app.id}-int-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "gfaSqm",
      label: "Jumlah Luas Lantai Kasar / GFA (m²)",
      category: "INTENSITY" as const,
      value: Math.round(app.siteAreaSqm * 1.8),
      unit: "SQM",
      normalizedValue: Math.round(app.siteAreaSqm * 1.8),
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: Math.round(app.siteAreaSqm * 1.8),
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 8,
          quotedText: `Gross Floor Area (GFA) keseluruhan bangunan adalah ${Math.round(app.siteAreaSqm * 1.8).toLocaleString()} m².`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-int-3`,
      factId: `fact-${app.id}-int-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "plinthCoverage",
      label: "Liputan Tapak / Plinth Area (%)",
      category: "INTENSITY" as const,
      value: "58.5%",
      unit: "PERCENT",
      normalizedValue: 58.5,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.94,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "58.5%",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 9,
          quotedText: `Liputan plinth bangunan dicadangkan pada kadar 58.5% dari luas tapak bersih.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 5. BUILDING
    {
      id: `fact-${app.id}-bldg-1`,
      factId: `fact-${app.id}-bldg-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "buildingStoreys",
      label: "Bilangan Tingkat Bangunan",
      category: "BUILDING" as const,
      value: isApp3 ? "3 Tingkat" : isApp2 ? "2 Tingkat" : "8 Tingkat",
      unit: "TINGKAT",
      normalizedValue: isApp3 ? 3 : isApp2 ? 2 : 8,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: isApp3 ? "3 Tingkat" : isApp2 ? "2 Tingkat" : "8 Tingkat",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 10,
          quotedText: `Struktur bangunan terdiri daripada ${isApp3 ? "3" : isApp2 ? "2" : "8"} tingkat utama.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-bldg-2`,
      factId: `fact-${app.id}-bldg-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "frontSetback",
      label: "Anjakan Bangunan Hadapan (m)",
      category: "BUILDING" as const,
      value: isApp2 ? 4.5 : 7.5,
      unit: "METER",
      normalizedValue: isApp2 ? 4.5 : 7.5,
      status: isApp2 ? ("CONFLICT" as const) : ("MANUALLY_CONFIRMED" as const),
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: isApp2 ? 4.5 : 7.5,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 11,
          quotedText: `Anjakan bangunan hadapan dari rezab jalan utama: ${isApp2 ? "4.50" : "7.50"} meter.`,
          tableReference: "Jadual Anjakan Bangunan",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-bldg-3`,
      factId: `fact-${app.id}-bldg-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "sideSetback",
      label: "Anjakan Bangunan Sisi & Belakang (m)",
      category: "BUILDING" as const,
      value: 6.0,
      unit: "METER",
      normalizedValue: 6.0,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: 6.0,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 11,
          quotedText: `Anjakan sisi dan belakang adalah 6.00 meter mematuhi kelebaran zon penampan.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 6. PARKING
    {
      id: `fact-${app.id}-park-1`,
      factId: `fact-${app.id}-park-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "parkingBays",
      label: "Tempat Letak Kereta (Petak)",
      category: "PARKING" as const,
      value: isApp3 ? 85 : 135,
      unit: "PETAK",
      normalizedValue: isApp3 ? 85 : 135,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: isApp3 ? 85 : 135,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 13,
          quotedText: `Penyediaan petak letak kereta: ${isApp3 ? "85" : "135"} petak.`,
          tableReference: "Jadual TLK",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-park-2`,
      factId: `fact-${app.id}-park-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "motorcycleBays",
      label: "Petak Letak Motosikal (Petak)",
      category: "PARKING" as const,
      value: 30,
      unit: "PETAK",
      normalizedValue: 30,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: 30,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 13,
          quotedText: `Petak motosikal disediakan sebanyak 30 petak berbumbung.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-park-3`,
      factId: `fact-${app.id}-park-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "okuParkingBays",
      label: "Petak Letak Kereta OKU (Petak)",
      category: "PARKING" as const,
      value: 3,
      unit: "PETAK",
      normalizedValue: 3,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: 3,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 13,
          quotedText: `3 petak khas orang kurang upaya (OKU) disediakan berdekatan lobi lif utama.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 7. OPEN_SPACE
    {
      id: `fact-${app.id}-open-1`,
      factId: `fact-${app.id}-open-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "openSpacePercentage",
      label: "Peratusan Kawasan Lapang Awam (%)",
      category: "OPEN_SPACE" as const,
      value: "10.5%",
      unit: "PERCENT",
      normalizedValue: 10.5,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "10.5%",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 15,
          quotedText: `Peruntukan kawasan lapang berfungsi adalah 10.5% daripada jumlah keluasan skim pembangunan.`,
          tableReference: "Jadual Kawasan Lapang",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-open-2`,
      factId: `fact-${app.id}-open-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "greenAreaSqm",
      label: "Keluasan Kawasan Hijau & Rekreasi (m²)",
      category: "OPEN_SPACE" as const,
      value: Math.round(app.siteAreaSqm * 0.11),
      unit: "SQM",
      normalizedValue: Math.round(app.siteAreaSqm * 0.11),
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: Math.round(app.siteAreaSqm * 0.11),
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 15,
          quotedText: `Keluasan landskap lembut dan zon hijau ialah ${Math.round(app.siteAreaSqm * 0.11).toLocaleString()} m².`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 8. ACCESS
    {
      id: `fact-${app.id}-acc-1`,
      factId: `fact-${app.id}-acc-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "roadReserveWidth",
      label: "Kelebaran Rizab Jalan Masuk Utama (m)",
      category: "ACCESS" as const,
      value: "20.0 m (66 kaki)",
      unit: "METER",
      normalizedValue: 20.0,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "20.0 m (66 kaki)",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 17,
          quotedText: `Laluan keluar masuk utama disambungkan ke jalan protokol dengan rezab selebar 20.0 meter.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-acc-2`,
      factId: `fact-${app.id}-acc-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "pedestrianWalkway",
      label: "Laluan Pejalan Kaki & OKU",
      category: "ACCESS" as const,
      value: "Laluan Berturap 1.5m Bersambung",
      unit: null,
      normalizedValue: "Laluan Berturap 1.5m",
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.94,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "Laluan Berturap 1.5m Bersambung",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 17,
          quotedText: `Penyediaan laluan pejalan kaki mesra OKU selebar 1.5 meter di sepanjang perimeter tapak.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
  ];
}

export function getDemoGisForApp(id: string) {
  const app = getDemoApplication(id);
  const siteArea = app.siteAreaSqm;

  const site = {
    id: `site-${app.id}-01`,
    applicationId: app.id,
    siteType: "SINGLE_LOT" as const,
    latitude: app.latitude,
    longitude: app.longitude,
    selectedLotIds: [`lot-${app.id}-cad`],
    lotNumbers: [app.lotNo],
    mukim: app.mukim,
    district: "Langkawi",
    cadastralAreaSqm: siteArea,
    combinedLotAreaSqm: siteArea,
    geometrySource: "CADASTRAL" as const,
    verificationStatus: "OFFICER_VERIFIED" as const,
    verifiedBy: "demo-officer-uid",
    verifiedAt: app.updatedAt,
    verificationComment: `Tapak telah disahkan oleh Pegawai GIS MPLBP selaras dengan Lot ${app.lotNo}, Mukim ${app.mukim}.`,
    siteVersion: 1,
    spatialAnalysisVersion: "GIS_ENGINE_V1.0",
    createdAt: app.createdAt,
    updatedAt: app.updatedAt,
  };

  const comparison = {
    lcpLotNumber: app.lotNo,
    gisLotNumber: app.lotNo,
    lotMatch: true,
    lcpMukim: app.mukim,
    gisMukim: app.mukim,
    mukimMatch: true,
    lcpSiteAreaSqm: siteArea,
    gisSiteAreaSqm: siteArea,
    differenceSqm: 0,
    differencePercent: 0,
    status: "MATCH" as const,
  };

  const rtdData = {
    primaryZone: {
      zoneId: `zone-${app.id}-01`,
      zoneCode: "BP2-KM-01",
      zoneName: `Zon Pembangunan ${app.developmentType} (Perniagaan & Kediaman)`,
      zoneCategory: app.developmentCategory === "COMMERCIAL" ? "PERNIAGAAN" : "KEDIAMAN",
      intersectionAreaSqm: Math.round(siteArea * 0.85),
      intersectionPercent: 85,
      datasetVersion: "RTD_LANGKAWI_2030_V2.1",
    },
    zones: [
      {
        zoneId: `zone-${app.id}-01`,
        zoneCode: "BP2-KM-01",
        zoneName: `Zon Pembangunan ${app.developmentType} (Perniagaan & Kediaman)`,
        zoneCategory: app.developmentCategory === "COMMERCIAL" ? "PERNIAGAAN" : "KEDIAMAN",
        intersectionAreaSqm: Math.round(siteArea * 0.85),
        intersectionPercent: 85,
        datasetVersion: "RTD_LANGKAWI_2030_V2.1",
      },
      {
        zoneId: `zone-${app.id}-02`,
        zoneCode: "BP2-INF-02",
        zoneName: "Zon Pengangkutan, Rizab Jalan & Utiliti Awam",
        zoneCategory: "INFRASTRUKTUR",
        intersectionAreaSqm: Math.round(siteArea * 0.15),
        intersectionPercent: 15,
        datasetVersion: "RTD_LANGKAWI_2030_V2.1",
      },
    ],
  };

  // Tailor nearby features based on Mukim & Location
  let features = [
    {
      featureId: `feat-${app.id}-01`,
      featureType: "HOTEL",
      featureName: "Adya Hotel Langkawi",
      distanceMeters: 220,
      datasetVersion: "POI_LANGKAWI_2026",
    },
    {
      featureId: `feat-${app.id}-02`,
      featureType: "ROAD",
      featureName: "Jalan Persiaran Kuah (Rizab 66 kaki / 20m)",
      distanceMeters: 45,
      datasetVersion: "JALAN_JKR_2026",
    },
    {
      featureId: `feat-${app.id}-03`,
      featureType: "SCHOOL",
      featureName: "SK Mahsuri Kuah",
      distanceMeters: 420,
      datasetVersion: "POI_LANGKAWI_2026",
    },
    {
      featureId: `feat-${app.id}-04`,
      featureType: "PUBLIC_FACILITY",
      featureName: "Masjid Al-Hana Kuah",
      distanceMeters: 480,
      datasetVersion: "POI_LANGKAWI_2026",
    },
  ];

  if (app.mukim.toLowerCase().includes("kedawang") || app.mukim.toLowerCase().includes("cenang")) {
    features = [
      {
        featureId: `feat-${app.id}-01`,
        featureType: "HOTEL",
        featureName: "Pelangi Beach Resort & Spa Langkawi",
        distanceMeters: 180,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-02`,
        featureType: "ROAD",
        featureName: "Jalan Pantai Cenang (Rizab 66 kaki / 20m)",
        distanceMeters: 30,
        datasetVersion: "JALAN_JKR_2026",
      },
      {
        featureId: `feat-${app.id}-03`,
        featureType: "SCHOOL",
        featureName: "SK Kedawang",
        distanceMeters: 380,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-04`,
        featureType: "PUBLIC_FACILITY",
        featureName: "Klinik Kesihatan Pantai Cenang",
        distanceMeters: 450,
        datasetVersion: "POI_LANGKAWI_2026",
      },
    ];
  } else if (app.mukim.toLowerCase().includes("ayer") || app.mukim.toLowerCase().includes("hangat")) {
    features = [
      {
        featureId: `feat-${app.id}-01`,
        featureType: "HOTEL",
        featureName: "Tanjung Rhu Luxury Resort",
        distanceMeters: 320,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-02`,
        featureType: "ROAD",
        featureName: "Jalan Teluk Ewa - Ayer Hangat (Rizab 66 kaki)",
        distanceMeters: 50,
        datasetVersion: "JALAN_JKR_2026",
      },
      {
        featureId: `feat-${app.id}-03`,
        featureType: "PUBLIC_FACILITY",
        featureName: "Jeti Perikanan LKIM Teluk Ewa",
        distanceMeters: 280,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-04`,
        featureType: "SCHOOL",
        featureName: "SK Ayer Hangat",
        distanceMeters: 410,
        datasetVersion: "POI_LANGKAWI_2026",
      },
    ];
  } else if (app.mukim.toLowerCase().includes("matsirat")) {
    features = [
      {
        featureId: `feat-${app.id}-01`,
        featureType: "PUBLIC_FACILITY",
        featureName: "Lapangan Terbang Antarabangsa Langkawi (LGK)",
        distanceMeters: 650,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-02`,
        featureType: "ROAD",
        featureName: "Jalan Lapangan Terbang (Rizab 100 kaki / 30m)",
        distanceMeters: 40,
        datasetVersion: "JALAN_JKR_2026",
      },
      {
        featureId: `feat-${app.id}-03`,
        featureType: "COMMERCIAL_AREA",
        featureName: "Mahsuri International Exhibition Centre (MIEC)",
        distanceMeters: 490,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-04`,
        featureType: "SCHOOL",
        featureName: "SK Padang Matsirat",
        distanceMeters: 350,
        datasetVersion: "POI_LANGKAWI_2026",
      },
    ];
  } else if (app.mukim.toLowerCase().includes("melaka")) {
    features = [
      {
        featureId: `feat-${app.id}-01`,
        featureType: "TOURISM_AREA",
        featureName: "Pusat Rekreasi Lubuk Semilang & Air Terjun",
        distanceMeters: 520,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-02`,
        featureType: "ROAD",
        featureName: "Jalan Ulu Melaka (Rizab 66 kaki / 20m)",
        distanceMeters: 60,
        datasetVersion: "JALAN_JKR_2026",
      },
      {
        featureId: `feat-${app.id}-03`,
        featureType: "SCHOOL",
        featureName: "SK Ulu Melaka",
        distanceMeters: 430,
        datasetVersion: "POI_LANGKAWI_2026",
      },
      {
        featureId: `feat-${app.id}-04`,
        featureType: "PUBLIC_FACILITY",
        featureName: "Masjid Nurul Huda Ulu Melaka",
        distanceMeters: 470,
        datasetVersion: "POI_LANGKAWI_2026",
      },
    ];
  }

  const bufferData = {
    bufferDistanceMeters: 500,
    featuresCountByType: {
      HOTEL: features.filter((f) => f.featureType === "HOTEL").length,
      ROAD: features.filter((f) => f.featureType === "ROAD").length,
      SCHOOL: features.filter((f) => f.featureType === "SCHOOL").length,
      PUBLIC_FACILITY: features.filter((f) => f.featureType === "PUBLIC_FACILITY").length,
      COMMERCIAL_AREA: features.filter((f) => f.featureType === "COMMERCIAL_AREA").length,
      TOURISM_AREA: features.filter((f) => f.featureType === "TOURISM_AREA").length,
    },
    features,
  };

  return { site, comparison, rtdData, bufferData };
}

export function getDemoIssuesForApp(id: string) {
  const app = getDemoApplication(id);
  if (app.id === "app-demo-002") {
    return [
      {
        issueId: `issue-${app.id}-setback`,
        applicationId: app.id,
        ruleId: "RTD-SETBACK-01",
        title: "Isu Anjakan Hadapan Bangunan Kurang Daripada 6.0 Meter",
        description: "Anjakan bangunan hadapan pada Pelan Susunatur hanya menyediakan 4.50m berbanding syarat 6.00m dari rizab jalan utama.",
        category: "SETBACK",
        severity: "HIGH",
        status: "OPEN",
        visibility: "INTERNAL",
        createdAt: app.createdAt,
        updatedAt: app.updatedAt,
        identifiedBy: "SMARTCHECK_ENGINE",
      },
    ];
  }

  if (app.id === "app-demo-003") {
    return [
      {
        issueId: `issue-${app.id}-parking`,
        applicationId: app.id,
        ruleId: "RTD-PARKING-01",
        title: "Kekurangan 25 Petak Tempat Letak Kereta Komersial",
        description: "Penyediaan 85 petak tempat letak kereta tidak mencukupi kiraan minima 110 petak bagi kompleks perniagaan 3 tingkat.",
        category: "PARKING",
        severity: "MEDIUM",
        status: "PUBLISHED_TO_APPLICANT",
        visibility: "APPLICANT_VISIBLE",
        createdAt: app.createdAt,
        updatedAt: app.updatedAt,
        identifiedBy: "OFFICER_REVIEW",
      },
    ];
  }

  return [];
}

