export interface DemoApplicationSeed {
  id: string;
  applicationNo: string;
  title: string;
  developmentType: string;
  developmentCategory: string;
  mukim: string;
  lotNo: string;
  status: string;
  currentVersion: number;
  applicantUid: string;
  applicantName: string;
  consultantName: string;
  estimatedCost: number;
  latitude: number;
  longitude: number;
  siteAreaSqm: number;
  createdAt: string;
  updatedAt: string;
  remarks: string;
  // Sub-collection items
  issuesCount: number;
  complianceScore: number;
}

export const DEMO_5_APPLICATIONS: DemoApplicationSeed[] = [
  {
    id: "app-demo-001",
    applicationNo: "KM/2026/000101",
    title: "Cadangan Pembangunan Resort Mewah 5 Bintang (120 Bilik) di Pantai Chenang",
    developmentType: "HOTEL",
    developmentCategory: "PELANCONGAN",
    mukim: "Kedawang",
    lotNo: "Lot 1042",
    status: "COMPLETED",
    currentVersion: 2,
    applicantUid: "demo-applicant-uid",
    applicantName: "Perunding Arkitek Langkawi Sdn Bhd",
    consultantName: "Ar. Ahmad Zulkifli (LAM A/1245)",
    estimatedCost: 45000000,
    latitude: 6.2915,
    longitude: 99.7289,
    siteAreaSqm: 18500,
    createdAt: "2026-06-01T08:30:00Z",
    updatedAt: "2026-08-10T14:20:00Z",
    remarks: "Permohonan selesai diproses sepenuhnya dan Laporan Rasmi PDF diterbitkan.",
    issuesCount: 0,
    complianceScore: 100,
  },
  {
    id: "app-demo-002",
    applicationNo: "KM/2026/000102",
    title: "Cadangan Skim Perumahan Mampu Milik (80 Unit Rumah Teres 2 Tingkat)",
    developmentType: "HOUSING",
    developmentCategory: "PERUMAHAN",
    mukim: "Kuah",
    lotNo: "Lot 3241",
    status: "OFFICER_REVIEW",
    currentVersion: 1,
    applicantUid: "demo-applicant-uid",
    applicantName: "Pembinaan Seri Kedah Sdn Bhd",
    consultantName: "Ar. Siti Fatimah (LAM A/1890)",
    estimatedCost: 28000000,
    latitude: 6.3265,
    longitude: 99.8432,
    siteAreaSqm: 24000,
    createdAt: "2026-07-15T09:00:00Z",
    updatedAt: "2026-08-16T11:45:00Z",
    remarks: "Pegawai perancang sedang menilai isu anjakan hadapan bangunan.",
    issuesCount: 1,
    complianceScore: 85,
  },
  {
    id: "app-demo-003",
    applicationNo: "KM/2026/000103",
    title: "Cadangan Kompleks Komersial & Bazar Bebas Cukai (3 Tingkat)",
    developmentType: "COMMERCIAL",
    developmentCategory: "PERDAGANGAN",
    mukim: "Kuah",
    lotNo: "Lot 512",
    status: "REQUEST_INFORMATION",
    currentVersion: 1,
    applicantUid: "demo-applicant-uid",
    applicantName: "Syarikat Niaga Mahsuri Sdn Bhd",
    consultantName: "Ar. Tan Boon Huat (LAM A/2104)",
    estimatedCost: 16500000,
    latitude: 6.3198,
    longitude: 99.8512,
    siteAreaSqm: 9200,
    createdAt: "2026-07-20T10:15:00Z",
    updatedAt: "2026-08-14T16:30:00Z",
    remarks: "Pegawai OSC mengeluarkan RFI bagi pindaan kapasiti tempat letak kereta.",
    issuesCount: 2,
    complianceScore: 70,
  },
  {
    id: "app-demo-004",
    applicationNo: "KM/2026/000104",
    title: "Cadangan Pembangunan Bercampur (Pangsapuri Servis & Ruang Niaga Maritim)",
    developmentType: "MIXED_DEVELOPMENT",
    developmentCategory: "PEMBANGUNAN_BERCAMPUR",
    mukim: "Padang Matsirat",
    lotNo: "Lot 889",
    status: "RESUBMITTED",
    currentVersion: 2,
    applicantUid: "demo-applicant-uid",
    applicantName: "Marina Bay Langkawi Development Ltd",
    consultantName: "Ar. David Wong (LAM A/1550)",
    estimatedCost: 62000000,
    latitude: 6.3541,
    longitude: 99.7188,
    siteAreaSqm: 31000,
    createdAt: "2026-06-25T11:00:00Z",
    updatedAt: "2026-08-17T09:10:00Z",
    remarks: "Pemohon telah memuat naik pelan pinda LCP v2 berikutan ulasan teknikal.",
    issuesCount: 1,
    complianceScore: 90,
  },
  {
    id: "app-demo-005",
    applicationNo: "KM/2026/000105",
    title: "Cadangan Pusat Pemprosesan Makanan Laut & Gudang Logistik Sejuk Beku",
    developmentType: "INDUSTRIAL",
    developmentCategory: "INDUSTRI",
    mukim: "Ayer Hangat",
    lotNo: "Lot 1503",
    status: "VERIFIED",
    currentVersion: 1,
    applicantUid: "demo-applicant-uid",
    applicantName: "Langkawi Fisheries Logistics Sdn Bhd",
    consultantName: "Ir. Mohd Ridzuan (BEM 28411)",
    estimatedCost: 12000000,
    latitude: 6.4182,
    longitude: 99.8214,
    siteAreaSqm: 14500,
    createdAt: "2026-08-01T14:00:00Z",
    updatedAt: "2026-08-18T10:00:00Z",
    remarks: "Semakan enjin peraturan SmartCheck selesai dan disahkan pegawai.",
    issuesCount: 0,
    complianceScore: 100,
  },
];

// Alias for backwards compatibility
export const DEMO_10_APPLICATIONS = DEMO_5_APPLICATIONS;

export function getDemoApplication(id: string): DemoApplicationSeed {
  return DEMO_10_APPLICATIONS.find((a) => a.id === id || a.applicationNo === id) || DEMO_10_APPLICATIONS[0];
}

export function getDemoSmartCheckForApp(id: string) {
  const app = getDemoApplication(id);
  const isApp2 = app.id === "app-demo-002" || app.id === "app-demo-02";
  const isApp3 = app.id === "app-demo-003" || app.id === "app-demo-03";

  return [
    {
      ruleId: "RTD-ZONING-01",
      ruleCode: "RTD-ZONING-01",
      ruleName: "Pematuhan Pengezonan Guna Tanah RTD 2030",
      ruleSetId: "ruleset-langkawi-2030",
      ruleSetVersion: "1.0.0",
      category: "RTD",
      status: "COMPLIANT" as const,
      severity: "CRITICAL" as const,
      actualValue: app.developmentCategory,
      requiredValue: `Zon ${app.developmentCategory} / Bercampur`,
      difference: null,
      unit: "ZON",
      messageCode: "ZONING_MATCH",
      messageText: `Guna tanah ${app.developmentCategory} selaras dengan Rancangan Tempatan Daerah Langkawi 2030 (Mukim ${app.mukim}).`,
      inputEvidence: [
        {
          key: "proposedLandUse",
          value: app.title,
          sourceType: "LCP_CONFIRMED_FACT" as const,
          isConfirmed: true,
        },
      ],
      ruleEvidence: {
        sourceDocumentId: "Rancangan Tempatan Daerah Langkawi 2030",
        sourceDocumentVersion: "1.0",
        sourceClause: "Klausa 4.2 (Jadual Pengezonan)",
        sourcePage: 48,
        sourceTextExcerpt: "Pembangunan dibenarkan selaras dengan peruntukan zon guna tanah yang diwartakan.",
      },
      requiresOfficerReview: false,
      evaluatedAt: app.updatedAt,
      engineVersion: "1.0.0",
    },
    {
      ruleId: "RTD-SETBACK-01",
      ruleCode: "RTD-SETBACK-01",
      ruleName: "Anjakan Hadapan Bangunan Minimum 6.0 Meter",
      ruleSetId: "ruleset-langkawi-2030",
      ruleSetVersion: "1.0.0",
      category: "SETBACK",
      status: (isApp2 ? "NON_COMPLIANT" : "COMPLIANT") as "NON_COMPLIANT" | "COMPLIANT",
      severity: "HIGH" as const,
      actualValue: isApp2 ? "4.50" : "7.50",
      requiredValue: "6.00",
      difference: isApp2 ? -1.5 : 1.5,
      unit: "METER",
      messageCode: isApp2 ? "SETBACK_INSUFFICIENT" : "SETBACK_COMPLIANT",
      messageText: isApp2
        ? "Anjakan bangunan hadapan tidak mencukupi rizab jalan minimum 6.0m (Defisit 1.50m)."
        : "Anjakan bangunan hadapan mematuhi kehendak minimum rizab jalan utama.",
      inputEvidence: [
        {
          key: "frontSetback",
          value: isApp2 ? 4.5 : 7.5,
          sourceType: "LCP_EXTRACTED_FACT" as const,
          isConfirmed: true,
        },
      ],
      ruleEvidence: {
        sourceDocumentId: "Undang-Undang Kecil Bangunan Seragam (UKBS 1984)",
        sourceDocumentVersion: "1.0",
        sourceClause: "UKBS Klausa 38(1)",
        sourcePage: 24,
        sourceTextExcerpt: "Setiap bangunan yang didirikan hendaklah mempunyai anjakan hadapan tidak kurang daripada 6.0 meter dari garis rizab jalan.",
      },
      requiresOfficerReview: isApp2,
      evaluatedAt: app.updatedAt,
      engineVersion: "1.0.0",
    },
    {
      ruleId: "RTD-PARKING-01",
      ruleCode: "RTD-PARKING-01",
      ruleName: "Penyediaan Tempat Letak Kereta Mengikut Nisbah Piawaian",
      ruleSetId: "ruleset-langkawi-2030",
      ruleSetVersion: "1.0.0",
      category: "PARKING",
      status: (isApp3 ? "NON_COMPLIANT" : "COMPLIANT") as "NON_COMPLIANT" | "COMPLIANT",
      severity: "MEDIUM" as const,
      actualValue: isApp3 ? "85" : "135",
      requiredValue: isApp3 ? "110" : "120",
      difference: isApp3 ? -25 : 15,
      unit: "PETAK",
      messageCode: isApp3 ? "PARKING_DEFICIT" : "PARKING_COMPLIANT",
      messageText: isApp3
        ? "Kapasiti tempat letak kereta kurang 25 petak daripada keperluan minima piawaian komersial."
        : "Kapasiti tempat letak kereta mencukupi termasuk petak OKU dan kenderaan elektrik (EV).",
      inputEvidence: [
        {
          key: "parkingBays",
          value: isApp3 ? 85 : 135,
          sourceType: "LCP_EXTRACTED_FACT" as const,
          isConfirmed: true,
        },
      ],
      ruleEvidence: {
        sourceDocumentId: "Piawaian Perancangan Tempat Letak Kereta Negeri Kedah",
        sourceDocumentVersion: "1.0",
        sourceClause: "Piawaian 3.1 (Perniagaan & Kediaman)",
        sourcePage: 15,
        sourceTextExcerpt: "Penyediaan tempat letak kereta hendaklah mematuhi nisbah keluasan lantai kasar bangunan.",
      },
      requiresOfficerReview: isApp3,
      evaluatedAt: app.updatedAt,
      engineVersion: "1.0.0",
    },
    {
      ruleId: "RTD-GREEN-01",
      ruleCode: "RTD-GREEN-01",
      ruleName: "Penyediaan Kawasan Lapang & Zon Hijau Minimum 10%",
      ruleSetId: "ruleset-langkawi-2030",
      ruleSetVersion: "1.0.0",
      category: "OPEN_SPACE",
      status: "COMPLIANT" as const,
      severity: "MEDIUM" as const,
      actualValue: "12.4",
      requiredValue: "10.0",
      difference: 2.4,
      unit: "%",
      messageCode: "GREEN_SPACE_COMPLIANT",
      messageText: "Zon hijau dan landskap lembut melebihi peratusan minimum yang ditetapkan.",
      inputEvidence: [
        {
          key: "openSpacePercentage",
          value: 12.4,
          sourceType: "LCP_EXTRACTED_FACT" as const,
          isConfirmed: true,
        },
      ],
      ruleEvidence: {
        sourceDocumentId: "Garis Panduan Landskap & Kawasan Lapang Negeri Kedah",
        sourceDocumentVersion: "1.0",
        sourceClause: "Klausa 2.1 (Rizab Kawasan Lapang)",
        sourcePage: 10,
        sourceTextExcerpt: "Pembangunan melebihi 1 ekar wajib memperuntukkan sekurang-kurangnya 10% kawasan lapang berfungsi.",
      },
      requiresOfficerReview: false,
      evaluatedAt: app.updatedAt,
      engineVersion: "1.0.0",
    },
  ];
}

export function getDemoDocumentsForApp(id: string) {
  const app = getDemoApplication(id);
  return [
    {
      id: `doc-${app.id}-lcp`,
      documentId: `doc-${app.id}-lcp`,
      applicationId: app.id,
      documentType: "LCP" as const,
      fileName: `LCP_Pelan_Susunatur_${app.lotNo.replace(/\s+/g, "_")}_v${app.currentVersion}.0.pdf`,
      originalFileName: `LCP_Pelan_Susunatur_${app.lotNo.replace(/\s+/g, "_")}_v${app.currentVersion}.0.pdf`,
      storagePath: `applications/${app.id}/documents/LCP_v${app.currentVersion}.pdf`,
      version: app.currentVersion,
      isCurrent: true,
      fileSize: 14850200,
      mimeType: "application/pdf",
      checksum: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      status: "ACTIVE" as const,
      processingStatus: "COMPLETED" as const,
      supersedesDocumentId: null,
      uploadedBy: app.applicantUid,
      uploadedAt: app.createdAt,
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `doc-${app.id}-grant`,
      documentId: `doc-${app.id}-grant`,
      applicationId: app.id,
      documentType: "SITE_PLAN" as const,
      fileName: `Pelan_Tapak_${app.lotNo.replace(/\s+/g, "_")}_Mukim_${app.mukim}.pdf`,
      originalFileName: `Pelan_Tapak_${app.lotNo.replace(/\s+/g, "_")}_Mukim_${app.mukim}.pdf`,
      storagePath: `applications/${app.id}/documents/Pelan_Tapak.pdf`,
      version: 1,
      isCurrent: true,
      fileSize: 4250100,
      mimeType: "application/pdf",
      checksum: "8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
      status: "ACTIVE" as const,
      processingStatus: "COMPLETED" as const,
      supersedesDocumentId: null,
      uploadedBy: app.applicantUid,
      uploadedAt: app.createdAt,
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
  ];
}

export function getDemoFactsForApp(id: string) {
  const app = getDemoApplication(id);
  const isApp2 = app.id === "app-demo-002" || app.id === "app-demo-02";
  const isApp3 = app.id === "app-demo-003" || app.id === "app-demo-03";

  return [
    // 1. PROJECT
    {
      id: `fact-${app.id}-proj-1`,
      factId: `fact-${app.id}-proj-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "projectName",
      label: "Nama Projek Pemajuan",
      category: "PROJECT" as const,
      value: app.title,
      unit: null,
      normalizedValue: app.title,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.99,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.title,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 1,
          quotedText: `Tajuk Cadangan: ${app.title}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-proj-2`,
      factId: `fact-${app.id}-proj-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "applicantName",
      label: "Pemohon / Pemaju",
      category: "PROJECT" as const,
      value: app.applicantName,
      unit: null,
      normalizedValue: app.applicantName,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.applicantName,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 1,
          quotedText: `Pemaju: ${app.applicantName}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-proj-3`,
      factId: `fact-${app.id}-proj-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "consultantName",
      label: "Jururancang Bandar / Arkitek",
      category: "PROJECT" as const,
      value: app.consultantName,
      unit: null,
      normalizedValue: app.consultantName,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.consultantName,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 2,
          quotedText: `Disediakan oleh: ${app.consultantName}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-proj-4`,
      factId: `fact-${app.id}-proj-4`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "estimatedCost",
      label: "Anggaran Kos Pemajuan (RM)",
      category: "PROJECT" as const,
      value: app.estimatedCost,
      unit: "MYR",
      normalizedValue: app.estimatedCost,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.estimatedCost,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 3,
          quotedText: `Anggaran nilai keseluruhan projek adalah RM ${app.estimatedCost.toLocaleString()}.`,
          tableReference: "Jadual 1.2: Anggaran Kos",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 2. SITE
    {
      id: `fact-${app.id}-site-1`,
      factId: `fact-${app.id}-site-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "lotNo",
      label: "Nombor Lot Hakmilik",
      category: "SITE" as const,
      value: app.lotNo,
      unit: null,
      normalizedValue: app.lotNo,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.99,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.lotNo,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 3,
          quotedText: `Tapak cadangan terletak di ${app.lotNo}, Mukim ${app.mukim}, Langkawi.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-site-2`,
      factId: `fact-${app.id}-site-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "siteAreaSqm",
      label: "Keluasan Tapak (m²)",
      category: "SITE" as const,
      value: app.siteAreaSqm,
      unit: "SQM",
      normalizedValue: app.siteAreaSqm,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.99,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.siteAreaSqm,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 3,
          quotedText: `Jumlah keluasan tapak pemajuan adalah seluas ${app.siteAreaSqm.toLocaleString()} m².`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-site-3`,
      factId: `fact-${app.id}-site-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "landStatus",
      label: "Status Hakmilik & Pegangan",
      category: "SITE" as const,
      value: "Pajakan 99 Tahun (Leasehold)",
      unit: null,
      normalizedValue: "Pajakan 99 Tahun",
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "Pajakan 99 Tahun (Leasehold)",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 4,
          quotedText: `Status pegangan tanah adalah Pajakan 99 Tahun yang berakhir pada tahun 2115.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 3. LAND_USE
    {
      id: `fact-${app.id}-land-1`,
      factId: `fact-${app.id}-land-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "proposedLandUse",
      label: "Cadangan Guna Tanah Utama",
      category: "LAND_USE" as const,
      value: app.developmentType,
      unit: null,
      normalizedValue: app.developmentType,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: app.developmentType,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 5,
          quotedText: `Cadangan guna tanah yang dikemukakan adalah bagi tujuan ${app.developmentType}.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-land-2`,
      factId: `fact-${app.id}-land-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "rtdZoning",
      label: "Pengezonan RTD Langkawi 2030",
      category: "LAND_USE" as const,
      value: `Zon Pembangunan ${app.developmentType} (Blok Perancangan BP 2)`,
      unit: null,
      normalizedValue: app.developmentType,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: `Zon Pembangunan ${app.developmentType} (Blok Perancangan BP 2)`,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 6,
          quotedText: `Menurut Rancangan Tempatan Daerah Langkawi 2030, tapak berada dalam zon pemajuan yang dibenarkan.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 4. INTENSITY
    {
      id: `fact-${app.id}-int-1`,
      factId: `fact-${app.id}-int-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "plotRatio",
      label: "Nisbah Plot (Plot Ratio)",
      category: "INTENSITY" as const,
      value: "1 : 2.5",
      unit: "RATIO",
      normalizedValue: 2.5,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "1 : 2.5",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 8,
          quotedText: `Nisbah plot yang dicadangkan ialah 1:2.5 selaras dengan piawaian kelas guna tanah.`,
          tableReference: "Jadual Intensiti Pembangunan",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-int-2`,
      factId: `fact-${app.id}-int-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "gfaSqm",
      label: "Jumlah Luas Lantai Kasar / GFA (m²)",
      category: "INTENSITY" as const,
      value: Math.round(app.siteAreaSqm * 1.8),
      unit: "SQM",
      normalizedValue: Math.round(app.siteAreaSqm * 1.8),
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: Math.round(app.siteAreaSqm * 1.8),
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 8,
          quotedText: `Gross Floor Area (GFA) keseluruhan bangunan adalah ${Math.round(app.siteAreaSqm * 1.8).toLocaleString()} m².`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-int-3`,
      factId: `fact-${app.id}-int-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "plinthCoverage",
      label: "Liputan Tapak / Plinth Area (%)",
      category: "INTENSITY" as const,
      value: "58.5%",
      unit: "PERCENT",
      normalizedValue: 58.5,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.94,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "58.5%",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 9,
          quotedText: `Liputan plinth bangunan dicadangkan pada kadar 58.5% dari luas tapak bersih.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 5. BUILDING
    {
      id: `fact-${app.id}-bldg-1`,
      factId: `fact-${app.id}-bldg-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "buildingStoreys",
      label: "Bilangan Tingkat Bangunan",
      category: "BUILDING" as const,
      value: isApp3 ? "3 Tingkat" : isApp2 ? "2 Tingkat" : "8 Tingkat",
      unit: "TINGKAT",
      normalizedValue: isApp3 ? 3 : isApp2 ? 2 : 8,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: isApp3 ? "3 Tingkat" : isApp2 ? "2 Tingkat" : "8 Tingkat",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 10,
          quotedText: `Struktur bangunan terdiri daripada ${isApp3 ? "3" : isApp2 ? "2" : "8"} tingkat utama.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-bldg-2`,
      factId: `fact-${app.id}-bldg-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "frontSetback",
      label: "Anjakan Bangunan Hadapan (m)",
      category: "BUILDING" as const,
      value: isApp2 ? 4.5 : 7.5,
      unit: "METER",
      normalizedValue: isApp2 ? 4.5 : 7.5,
      status: isApp2 ? ("CONFLICT" as const) : ("MANUALLY_CONFIRMED" as const),
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: isApp2 ? 4.5 : 7.5,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 11,
          quotedText: `Anjakan bangunan hadapan dari rezab jalan utama: ${isApp2 ? "4.50" : "7.50"} meter.`,
          tableReference: "Jadual Anjakan Bangunan",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-bldg-3`,
      factId: `fact-${app.id}-bldg-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "sideSetback",
      label: "Anjakan Bangunan Sisi & Belakang (m)",
      category: "BUILDING" as const,
      value: 6.0,
      unit: "METER",
      normalizedValue: 6.0,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: 6.0,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 11,
          quotedText: `Anjakan sisi dan belakang adalah 6.00 meter mematuhi kelebaran zon penampan.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 6. PARKING
    {
      id: `fact-${app.id}-park-1`,
      factId: `fact-${app.id}-park-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "parkingBays",
      label: "Tempat Letak Kereta (Petak)",
      category: "PARKING" as const,
      value: isApp3 ? 85 : 135,
      unit: "PETAK",
      normalizedValue: isApp3 ? 85 : 135,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.96,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: isApp3 ? 85 : 135,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 13,
          quotedText: `Penyediaan petak letak kereta: ${isApp3 ? "85" : "135"} petak.`,
          tableReference: "Jadual TLK",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-park-2`,
      factId: `fact-${app.id}-park-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "motorcycleBays",
      label: "Petak Letak Motosikal (Petak)",
      category: "PARKING" as const,
      value: 30,
      unit: "PETAK",
      normalizedValue: 30,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: 30,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 13,
          quotedText: `Petak motosikal disediakan sebanyak 30 petak berbumbung.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-park-3`,
      factId: `fact-${app.id}-park-3`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "okuParkingBays",
      label: "Petak Letak Kereta OKU (Petak)",
      category: "PARKING" as const,
      value: 3,
      unit: "PETAK",
      normalizedValue: 3,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: 3,
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 13,
          quotedText: `3 petak khas orang kurang upaya (OKU) disediakan berdekatan lobi lif utama.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 7. OPEN_SPACE
    {
      id: `fact-${app.id}-open-1`,
      factId: `fact-${app.id}-open-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "openSpacePercentage",
      label: "Peratusan Kawasan Lapang Awam (%)",
      category: "OPEN_SPACE" as const,
      value: "10.5%",
      unit: "PERCENT",
      normalizedValue: 10.5,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.97,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "10.5%",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 15,
          quotedText: `Peruntukan kawasan lapang berfungsi adalah 10.5% daripada jumlah keluasan skim pembangunan.`,
          tableReference: "Jadual Kawasan Lapang",
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-open-2`,
      factId: `fact-${app.id}-open-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "greenAreaSqm",
      label: "Keluasan Kawasan Hijau & Rekreasi (m²)",
      category: "OPEN_SPACE" as const,
      value: Math.round(app.siteAreaSqm * 0.11),
      unit: "SQM",
      normalizedValue: Math.round(app.siteAreaSqm * 0.11),
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.95,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: Math.round(app.siteAreaSqm * 0.11),
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 15,
          quotedText: `Keluasan landskap lembut dan zon hijau ialah ${Math.round(app.siteAreaSqm * 0.11).toLocaleString()} m².`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },

    // 8. ACCESS
    {
      id: `fact-${app.id}-acc-1`,
      factId: `fact-${app.id}-acc-1`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "roadReserveWidth",
      label: "Kelebaran Rizab Jalan Masuk Utama (m)",
      category: "ACCESS" as const,
      value: "20.0 m (66 kaki)",
      unit: "METER",
      normalizedValue: 20.0,
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.98,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "20.0 m (66 kaki)",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 17,
          quotedText: `Laluan keluar masuk utama disambungkan ke jalan protokol dengan rezab selebar 20.0 meter.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
    {
      id: `fact-${app.id}-acc-2`,
      factId: `fact-${app.id}-acc-2`,
      applicationId: app.id,
      documentId: `doc-${app.id}-lcp`,
      documentVersion: app.currentVersion,
      key: "pedestrianWalkway",
      label: "Laluan Pejalan Kaki & OKU",
      category: "ACCESS" as const,
      value: "Laluan Berturap 1.5m Bersambung",
      unit: null,
      normalizedValue: "Laluan Berturap 1.5m",
      status: "MANUALLY_CONFIRMED" as const,
      confidence: 0.94,
      confidenceLevel: "HIGH" as const,
      aiGenerated: true,
      confirmedValue: "Laluan Berturap 1.5m Bersambung",
      confirmedBy: "demo-officer-uid",
      confirmedAt: app.updatedAt,
      sourceEvidence: [
        {
          documentId: `doc-${app.id}-lcp`,
          documentVersion: app.currentVersion,
          pageNumber: 17,
          quotedText: `Penyediaan laluan pejalan kaki mesra OKU selebar 1.5 meter di sepanjang perimeter tapak.`,
          tableReference: null,
        },
      ],
      createdAt: app.createdAt,
      updatedAt: app.updatedAt,
    },
  ];
}

