import { ManagementDashboardResponse } from "@/types/analytics";

export const INITIAL_MANAGEMENT_DATA: ManagementDashboardResponse = {
  metadata: {
    timeRange: {
      from: "2026-06-01",
      to: "2026-08-19",
      preset: "THIS_YEAR",
    },
    filtersApplied: {},
    dataFreshness: "REALTIME",
    generatedAt: "2026-08-19T10:00:00Z",
    schemaVersion: "1.0.0",
    sampleSize: 5,
    hasInsufficientData: false,
  },
  summaryKpis: {
    totalApplications: 5,
    activeApplications: 4,
    smartCheckCompletedCount: 2,
    revisionRequiredCount: 1,
    officerReviewRequiredCount: 1,
    openIssuesCount: 2,
    avgSmartCheckDurationSeconds: 38,
    avgOfficerReviewDurationHours: 4.2,
    humanVerificationRate: 100,
    ruleTraceabilityRate: 100,
  },
  applicationTrend: [
    {
      periodKey: "2026-06",
      periodLabel: "Jun 2026",
      totalCount: 2,
      breakdownByDevelopmentType: { HOTEL: 1, MIXED_DEVELOPMENT: 1 },
      breakdownByMukim: { Kedawang: 1, "Padang Matsirat": 1 },
      breakdownByStatus: { COMPLETED: 1, RESUBMITTED: 1 },
    },
    {
      periodKey: "2026-07",
      periodLabel: "Jul 2026",
      totalCount: 2,
      breakdownByDevelopmentType: { HOUSING: 1, COMMERCIAL: 1 },
      breakdownByMukim: { Kuah: 2 },
      breakdownByStatus: { OFFICER_REVIEW: 1, REQUEST_INFORMATION: 1 },
    },
    {
      periodKey: "2026-08",
      periodLabel: "Ogos 2026",
      totalCount: 1,
      breakdownByDevelopmentType: { INDUSTRIAL: 1 },
      breakdownByMukim: { "Ayer Hangat": 1 },
      breakdownByStatus: { VERIFIED: 1 },
    },
  ],
  statusDistribution: [
    { status: "COMPLETED", label: "Selesai (Laporan Rasmi)", count: 1, percentage: 20 },
    { status: "OFFICER_REVIEW", label: "Semakan Teknikal Pegawai", count: 1, percentage: 20 },
    { status: "REQUEST_INFORMATION", label: "Perlu Pindaan (RFI)", count: 1, percentage: 20 },
    { status: "RESUBMITTED", label: "Pelan Pinda Diserah Semula", count: 1, percentage: 20 },
    { status: "VERIFIED", label: "Disahkan Pegawai", count: 1, percentage: 20 },
  ],
  developmentTypeDistribution: [
    { type: "HOTEL", label: "Hotel & Resort Pelancongan", count: 1, percentage: 20 },
    { type: "HOUSING", label: "Skim Perumahan & Kediaman", count: 1, percentage: 20 },
    { type: "COMMERCIAL", label: "Pusat Komersial & Perniagaan", count: 1, percentage: 20 },
    { type: "MIXED_DEVELOPMENT", label: "Pembangunan Bercampur", count: 1, percentage: 20 },
    { type: "INDUSTRIAL", label: "Perindustrian & Logistik", count: 1, percentage: 20 },
  ],
  smartCheckStatusDistribution: [
    { status: "COMPLIANT", label: "Patuh Sepenuhnya", count: 3, percentage: 60 },
    { status: "NON_COMPLIANT", label: "Ketidakpatuhan Dikesan", count: 1, percentage: 20 },
    { status: "REQUIRES_REVIEW", label: "Budi Bicara Pegawai", count: 1, percentage: 20 },
  ],
  categoryCompliance: [
    {
      category: "ZONING",
      categoryName: "Pengezonan RTD & Guna Tanah",
      totalEvaluated: 5,
      compliantCount: 5,
      nonCompliantCount: 0,
      requiresReviewCount: 0,
      insufficientDataCount: 0,
      complianceRate: 100,
    },
    {
      category: "SETBACK",
      categoryName: "Anjakan Bangunan & Rezab Jalan",
      totalEvaluated: 5,
      compliantCount: 4,
      nonCompliantCount: 1,
      requiresReviewCount: 0,
      insufficientDataCount: 0,
      complianceRate: 80,
    },
    {
      category: "PLOT_RATIO",
      categoryName: "Nisbah Plot & Kawasan Plinth",
      totalEvaluated: 5,
      compliantCount: 4,
      nonCompliantCount: 1,
      requiresReviewCount: 0,
      insufficientDataCount: 0,
      complianceRate: 80,
    },
    {
      category: "PARKING",
      categoryName: "Tempat Letak Kereta & Motosikal",
      totalEvaluated: 5,
      compliantCount: 3,
      nonCompliantCount: 1,
      requiresReviewCount: 1,
      insufficientDataCount: 0,
      complianceRate: 60,
    },
    {
      category: "ENVIRONMENT",
      categoryName: "Ketinggian & Kawalan Alam Sekitar",
      totalEvaluated: 5,
      compliantCount: 4,
      nonCompliantCount: 0,
      requiresReviewCount: 1,
      insufficientDataCount: 0,
      complianceRate: 80,
    },
  ],
  topNonCompliance: [
    {
      ruleCode: "PARK-01",
      ruleName: "Kecukupan Tempat Letak Kereta (Piawaian Komersial)",
      category: "PARKING",
      timesEvaluated: 5,
      nonCompliantCount: 1,
      nonComplianceRate: 20,
      sampleDenominatorText: "1 daripada 5 permohonan dinilai",
      ruleVersion: "1.0.0",
    },
    {
      ruleCode: "SETBACK-02",
      ruleName: "Anjakan Sisi & Belakang Bangunan Bertingkat",
      category: "SETBACK",
      timesEvaluated: 5,
      nonCompliantCount: 1,
      nonComplianceRate: 20,
      sampleDenominatorText: "1 daripada 5 permohonan dinilai",
      ruleVersion: "1.0.0",
    },
  ],
  issueAgeing: {
    bucket_0_3_days: 1,
    bucket_4_7_days: 1,
    bucket_8_14_days: 0,
    bucket_15_30_days: 0,
    bucket_over_30_days: 0,
    totalOpenIssues: 2,
    medianAgeDays: 3.5,
  },
  officerWorkload: [
    {
      officerUid: "off-01",
      officerName: "Pn. Noor Aini binti Zakaria",
      role: "PLANNING_OFFICER",
      assignedApplicationsCount: 2,
      openIssuesCount: 1,
      pendingReviewCount: 1,
      verifiedCommentsCount: 1,
      medianReviewDurationHours: 4.0,
    },
    {
      officerUid: "off-02",
      officerName: "En. Azman bin Kassim",
      role: "OSC_OFFICER",
      assignedApplicationsCount: 2,
      openIssuesCount: 1,
      pendingReviewCount: 1,
      verifiedCommentsCount: 1,
      medianReviewDurationHours: 4.1,
    },
    {
      officerUid: "off-03",
      officerName: "En. Faizal bin Hashim",
      role: "GIS_OFFICER",
      assignedApplicationsCount: 1,
      openIssuesCount: 0,
      pendingReviewCount: 1,
      verifiedCommentsCount: 0,
      medianReviewDurationHours: 5.2,
    },
  ],
  processingTimes: {
    avgSubmissionToDocCheckHours: 4.2,
    avgDocCheckToSmartCheckMinutes: 25,
    avgSmartCheckToReviewHours: 1.5,
    avgReviewToCommentHours: 4.2,
    avgCommentToPublicationHours: 2.1,
    medianTotalTurnaroundDays: 4.2,
  },
  spatialSummary: {
    mukimDistribution: [
      {
        mukim: "Kuah",
        applicationCount: 2,
        activeCount: 2,
        topDevelopmentType: "COMMERCIAL",
        totalSiteAreaSqm: 33200,
      },
      {
        mukim: "Kedawang",
        applicationCount: 1,
        activeCount: 0,
        topDevelopmentType: "HOTEL",
        totalSiteAreaSqm: 18500,
      },
      {
        mukim: "Padang Matsirat",
        applicationCount: 1,
        activeCount: 1,
        topDevelopmentType: "MIXED_DEVELOPMENT",
        totalSiteAreaSqm: 31000,
      },
      {
        mukim: "Ayer Hangat",
        applicationCount: 1,
        activeCount: 1,
        topDevelopmentType: "INDUSTRIAL",
        totalSiteAreaSqm: 14500,
      },
    ],
    rtdZoneDistribution: [
      {
        zoneCode: "PB",
        zoneName: "Pusat Bandar & Perdagangan",
        applicationCount: 2,
        totalSiteAreaSqm: 33200,
      },
      {
        zoneCode: "PL",
        zoneName: "Pelancongan & Rekreasi",
        applicationCount: 1,
        totalSiteAreaSqm: 18500,
      },
      {
        zoneCode: "PR",
        zoneName: "Perumahan",
        applicationCount: 1,
        totalSiteAreaSqm: 24000,
      },
      {
        zoneCode: "IN",
        zoneName: "Perindustrian",
        applicationCount: 1,
        totalSiteAreaSqm: 14500,
      },
    ],
    verifiedSiteLocationsCount: 5,
    unresolvedGisLocationsCount: 0,
    multiLotApplicationsCount: 0,
    multiZoneApplicationsCount: 0,
    areaMismatchCount: 0,
  },
  aiGovernance: {
    aiDraftsGenerated: 5,
    manualDraftsCreated: 0,
    aiDraftsVerified: 5,
    aiDraftsEdited: 1,
    averageEditRatioPercent: 4.5,
    verifiedWithoutHumanCount: 0,
    humanVerificationRate: 100,
    governanceBreachDetected: false,
    ruleEvidenceTraceabilityRate: 100,
  },
  activeAlerts: [
    {
      alertId: "alt-001",
      alertType: "CRITICAL_ISSUE_BACKLOG",
      severity: "INFO",
      status: "OPEN",
      title: "Prestasi Piagam Pelanggan Cemerlang",
      message: "100% permohonan terkini diproses mendahului had masa 14 hari Piagam Pelanggan.",
      metric: "SLA_COMPLIANCE",
      threshold: 90,
      actualValue: 100,
      period: "Ogos 2026",
      createdAt: "2026-08-19T00:00:00Z",
    },
  ],
  targets: [
    {
      targetId: "tgt-001",
      kpiCode: "TOTAL_APPLICATIONS",
      targetName: "Sasaran Pematuhan Piagam Pelanggan KM",
      targetValue: 95,
      unit: "%",
      effectiveFrom: "2026-01-01",
      approvedBy: "YDP MPLBP",
      createdAt: "2026-01-01T00:00:00Z",
      updatedAt: "2026-08-19T00:00:00Z",
    },
  ],
  descriptiveInsights: [
    "Pematuhan Piagam Pelanggan 14-Hari Kekal Cemerlang pada kadar 100% merentasi 5 permohonan aktif.",
    "Mukim Kuah mendahului aktiviti permohonan dengan 40% bahagian pembangunan komersial dan perumahan.",
    "Kadar pengesahan manusia (Human-in-the-Loop) dan kebolehkesanan peraturan berada pada tahap 100%.",
  ],
};
