import type { KpiCode, KpiDefinition } from "../../types/analytics.ts";

export const KPI_REGISTRY_VERSION = "1.0.0";

/**
 * Authoritative Centralized Registry of Management KPIs
 * Ensures all calculations, units, formulas and versions are deterministic and traceable across MPLBP.
 */
export const KPI_DEFINITIONS: Record<KpiCode, KpiDefinition> = {
  TOTAL_APPLICATIONS: {
    kpiCode: "TOTAL_APPLICATIONS",
    name: "Jumlah Keseluruhan Permohonan",
    description: "Jumlah permohonan Kebenaran Merancang (KM) yang didaftarkan dalam tempoh masa terpilih.",
    formula: "COUNT(applications WHERE createdAt BETWEEN dateFrom AND dateTo)",
    source: "applications",
    unit: "Permohonan",
    aggregationType: "COUNT",
    allowedFilters: ["mukim", "developmentType", "applicationStatus"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  ACTIVE_APPLICATIONS: {
    kpiCode: "ACTIVE_APPLICATIONS",
    name: "Permohonan Aktif Dalam Pemprosesan",
    description: "Permohonan KM yang sedang dalam proses penilaian dan belum selesai atau ditolak.",
    formula: "COUNT(applications WHERE status NOT IN ('DRAFT', 'COMPLETED', 'REJECTED'))",
    source: "applications",
    unit: "Permohonan",
    aggregationType: "COUNT",
    allowedFilters: ["mukim", "developmentType", "assignedOfficerUid"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  SMARTCHECK_COMPLETED: {
    kpiCode: "SMARTCHECK_COMPLETED",
    name: "SmartCheck Selesai Dinilai",
    description: "Bilangan penilaian pra-semakan peraturan perancangan yang berjaya diselesaikan oleh enjin peraturan.",
    formula: "COUNT(smartChecks WHERE status == 'COMPLETED')",
    source: "smartChecks",
    unit: "Semakan",
    aggregationType: "COUNT",
    allowedFilters: ["developmentType", "mukim"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  REVISION_REQUIRED: {
    kpiCode: "REVISION_REQUIRED",
    name: "Perlu Pindaan Pemohon",
    description: "Bilangan permohonan yang mengandungi sekurang-kurangnya satu kriteria ketidakpatuhan perancangan mandatori.",
    formula: "COUNT(smartChecks WHERE overallStatus == 'FAIL_PRECHECK' OR nonCompliantCount > 0)",
    source: "smartChecks",
    unit: "Permohonan",
    aggregationType: "COUNT",
    allowedFilters: ["mukim", "developmentType", "ruleCategory"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  OFFICER_REVIEW_REQUIRED: {
    kpiCode: "OFFICER_REVIEW_REQUIRED",
    name: "Perlu Semakan & Penilaian Pegawai",
    description: "Bilangan permohonan yang memerlukan pertimbangan budi bicara atau semakan manual pegawai.",
    formula: "COUNT(smartChecks WHERE requiresReviewCount > 0 OR overallStatus == 'REVIEW_REQUIRED')",
    source: "smartChecks",
    unit: "Permohonan",
    aggregationType: "COUNT",
    allowedFilters: ["assignedOfficerUid", "ruleCategory"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  OPEN_ISSUES: {
    kpiCode: "OPEN_ISSUES",
    name: "Isu Perancangan Belum Selesai",
    description: "Jumlah isu pematuhan yang masih berstatus terbuka atau dalam semakan.",
    formula: "COUNT(issues WHERE status IN ('OPEN', 'IN_REVIEW', 'WAITING_APPLICANT'))",
    source: "issues",
    unit: "Isu",
    aggregationType: "COUNT",
    allowedFilters: ["severity", "category", "assignedOfficerUid"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  AVG_SMARTCHECK_DURATION: {
    kpiCode: "AVG_SMARTCHECK_DURATION",
    name: "Purata Tempoh Penilaian SmartCheck",
    description: "Purata masa yang diambil oleh enjin peraturan untuk menilai keseluruhan peraturan bagi satu permohonan.",
    formula: "AVG(completedAt - startedAt) in seconds",
    source: "smartChecks",
    unit: "Saat",
    aggregationType: "AVG",
    allowedFilters: ["developmentType"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  AVG_OFFICER_REVIEW_DURATION: {
    kpiCode: "AVG_OFFICER_REVIEW_DURATION",
    name: "Purata Tempoh Semakan Pegawai",
    description: "Purata masa dari selesai SmartCheck sehingga ulasan pegawai disahkan.",
    formula: "AVG(verifiedAt - smartCheckCompletedAt) in hours",
    source: "verifiedComments / assessments",
    unit: "Jam",
    aggregationType: "AVG",
    allowedFilters: ["assignedOfficerUid"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  HUMAN_VERIFICATION_RATE: {
    kpiCode: "HUMAN_VERIFICATION_RATE",
    name: "Kadar Pengesahan Manusia Mandatori",
    description: "Peratusan ulasan rasmi yang disahkan oleh pegawai manusia bertauliah sebelum penerbitan (Mandatori 100%).",
    formula: "(COUNT(publishedComments WITH verifiedByHuman) / COUNT(publishedComments)) * 100",
    source: "verifiedComments",
    unit: "%",
    aggregationType: "PERCENTAGE",
    allowedFilters: [],
    version: "1.0.0",
    status: "ACTIVE",
  },
  RULE_TRACEABILITY_RATE: {
    kpiCode: "RULE_TRACEABILITY_RATE",
    name: "Kadar Ketelusan Punca Kuasa Peraturan",
    description: "Peratusan dapatan peraturan yang mempunyai rujukan klausa dan dokumen bukti lengkap (Sasaran 100%).",
    formula: "(COUNT(results WITH ruleEvidence) / COUNT(results)) * 100",
    source: "results",
    unit: "%",
    aggregationType: "PERCENTAGE",
    allowedFilters: ["ruleCategory"],
    version: "1.0.0",
    status: "ACTIVE",
  },
  MANUAL_CORRECTION_RATE: {
    kpiCode: "MANUAL_CORRECTION_RATE",
    name: "Kadar Pembetulan Manual Fakta LCP",
    description: "Peratusan fakta diekstrak AI yang dibetulkan secara manual oleh pegawai berbanding jumlah fakta diekstrak.",
    formula: "(COUNT(factsManuallyCorrected) / COUNT(factsExtracted)) * 100",
    source: "facts",
    unit: "%",
    aggregationType: "PERCENTAGE",
    allowedFilters: [],
    version: "1.0.0",
    status: "ACTIVE",
  },
  REPORT_INTEGRITY_RATE: {
    kpiCode: "REPORT_INTEGRITY_RATE",
    name: "Kadar Integriti Rekod Laporan Digital",
    description: "Peratusan laporan PDF yang disahkan padan dengan checksum SHA-256 tanpa sebarang perubahan fizikal.",
    formula: "(COUNT(validChecksumReports) / COUNT(totalVerifiedReports)) * 100",
    source: "reports",
    unit: "%",
    aggregationType: "PERCENTAGE",
    allowedFilters: [],
    version: "1.0.0",
    status: "ACTIVE",
  },
};

export function getKpiDefinition(code: KpiCode): KpiDefinition | undefined {
  return KPI_DEFINITIONS[code];
}

export function listActiveKpis(): KpiDefinition[] {
  return Object.values(KPI_DEFINITIONS).filter((k) => k.status === "ACTIVE");
}
